#!/bin/bash
#################################################################################################################
#Host EKS CLUSTER via EKSCTL
#################################################################################################################
#create iam role and attach policy
#ECRfull access,EKSpolicy and IAM full access
apt-get update -y
apt install unzip -y
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
aws configure
#Install EKS Tool
curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
sudo mv /tmp/eksctl /usr/local/bin
eksctl version
Install Kubectl
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl 
kubectl version --client
ssh-keygen
#Create EKS Cluster
eksctl create cluster --name my-cluster --region us-east-1 --version 1.32 --vpc-public-subnets subnet-0008e6a1476419d21,subnet-043ba27959f2b92d4 --without-nodegroup
##############################################################################################################################
##Create a Node Group##
##############################################################################################################################
eksctl create nodegroup \
  --cluster my-cluster \
  --region us-east-1 \
  --name my-node-group \
  --node-ami-family Ubuntu2204 \
  --node-type t3.small \
  --subnet-ids subnet-0008e6a1476419d21,subnet-043ba27959f2b92d4 \
  --nodes 3 \
  --nodes-min 2 \
  --nodes-max 4 \
  --ssh-access \
  --ssh-public-key /root/.ssh/id_rsa.pub
 
#or you can make cluster in this way
################################################################################################################################
#eksctl create cluster --name milestone-2 --region us-east-1 --version 1.32 --node-type t2.small --nodes 3 --nodes-min 2 --nodes-max 4 --ssh-access --ssh-public-key /root/.ssh/id_rsa.pub
 
 
 
#When You want to delete cluster
#eksctl delete cluster --name my-cluster
#vim sneha.sh
   # chmod +x sneha.sh
    # ./sneha.sh
    #  vim deployment.yaml
    #  kubectl apply -f deployment.yaml
    #  kubectl get pods
    #  vim deployment.yaml
    #  vim deploy.yaml
    #  kubectl apply -f deploy.yaml
   #  kubectl get pods
   #  history
